export interface Tool {
  id: string;
  name: string;
  description: string;
  icon: string;
  category: string;
  color: string;
  website?: string;
}

// Every entry below is backed by RESUME (skills, an employer's technologies, or the
// summary). Do not add a tool that isn't — a portfolio claiming skills the CV does
// not support is exactly the problem this file used to have.

export const toolsData: Tool[] = [
  {
    id: 'rust',
    name: 'Rust',
    description: 'Systems language behind every backend I ship — safety and performance without a GC',
    icon: '🦀',
    category: 'Language',
    color: '#CE422B',
    website: 'https://rust-lang.org',
  },
  {
    id: 'dart',
    name: 'Dart',
    description: 'The language I write Flutter in, across mobile, desktop and web',
    icon: '🎯',
    category: 'Language',
    color: '#0175C2',
    website: 'https://dart.dev',
  },
  {
    id: 'go',
    name: 'Go',
    description: 'Working knowledge — used for services and tooling',
    icon: '🐹',
    category: 'Working Knowledge',
    color: '#00ADD8',
    website: 'https://go.dev',
  },
  {
    id: 'java',
    name: 'Java',
    description: 'Working knowledge, mostly on the Android side',
    icon: '☕',
    category: 'Working Knowledge',
    color: '#E76F00',
  },
  {
    id: 'cpp',
    name: 'C / C++',
    description: 'Working knowledge — native interop and platform-specific code',
    icon: '⚙️',
    category: 'Working Knowledge',
    color: '#00599C',
  },
  {
    id: 'assembly',
    name: 'Assembly',
    description: 'Working knowledge — low-level experimentation',
    icon: '🧮',
    category: 'Working Knowledge',
    color: '#B08D57',
  },
  {
    id: 'flutter',
    name: 'Flutter',
    description: 'Cross-platform UI toolkit — 5+ years across mobile, desktop and web',
    icon: '🦋',
    category: 'Flutter & Dart',
    color: '#02569B',
    website: 'https://flutter.dev',
  },
  {
    id: 'riverpod',
    name: 'Riverpod',
    description: 'My default state management, with codegen on Riverpod 2.5',
    icon: '💧',
    category: 'Flutter & Dart',
    color: '#4A78C8',
    website: 'https://riverpod.dev',
  },
  {
    id: 'provider',
    name: 'Provider',
    description: 'State management for older and simpler Flutter trees',
    icon: '📦',
    category: 'Flutter & Dart',
    color: '#5B8DEF',
  },
  {
    id: 'gorouter',
    name: 'GoRouter',
    description: 'Declarative routing — Go Router 14 in the account management app',
    icon: '🧭',
    category: 'Flutter & Dart',
    color: '#2E7CF6',
  },
  {
    id: 'freezed',
    name: 'Freezed',
    description: 'Immutable models and unions, Freezed 3 with codegen',
    icon: '🧊',
    category: 'Flutter & Dart',
    color: '#5AC8FA',
  },
  {
    id: 'material3',
    name: 'Material 3',
    description: 'Design system for the Flutter clients I build',
    icon: '🎨',
    category: 'Flutter & Dart',
    color: '#6750A4',
    website: 'https://m3.material.io',
  },
  {
    id: 'wearos',
    name: 'Wear OS',
    description: 'Flutter targeting watch form factors',
    icon: '⌚',
    category: 'Flutter & Dart',
    color: '#4285F4',
  },
  {
    id: 'isar',
    name: 'Isar',
    description: 'Fast local database for Flutter apps',
    icon: '💾',
    category: 'Database',
    color: '#7E57C2',
  },
  {
    id: 'tokio',
    name: 'Tokio',
    description: 'Async runtime under every Rust service I write',
    icon: '⚡',
    category: 'Rust Ecosystem',
    color: '#CE422B',
    website: 'https://tokio.rs',
  },
  {
    id: 'axum',
    name: 'Axum',
    description: 'My primary Rust web framework — 45+ REST endpoints at AKIJ iBOS',
    icon: '🌐',
    category: 'Rust Ecosystem',
    color: '#D2691E',
    website: 'https://github.com/tokio-rs/axum',
  },
  {
    id: 'actixweb',
    name: 'actix-web',
    description: 'Alternative Rust web framework',
    icon: '🎬',
    category: 'Rust Ecosystem',
    color: '#B7410E',
    website: 'https://actix.rs',
  },
  {
    id: 'rocket',
    name: 'Rocket',
    description: 'Rust web framework',
    icon: '🚀',
    category: 'Rust Ecosystem',
    color: '#D33847',
    website: 'https://rocket.rs',
  },
  {
    id: 'tonic',
    name: 'Tonic',
    description: 'gRPC over Rust — powers Akij Air Search',
    icon: '📡',
    category: 'Rust Ecosystem',
    color: '#8B4513',
  },
  {
    id: 'serde',
    name: 'Serde',
    description: 'Serialization across every Rust service',
    icon: '🔄',
    category: 'Rust Ecosystem',
    color: '#B8860B',
    website: 'https://serde.rs',
  },
  {
    id: 'sqlx',
    name: 'SQLx',
    description: 'Compile-time checked SQL against PostgreSQL',
    icon: '🗄️',
    category: 'Rust Ecosystem',
    color: '#4B0082',
  },
  {
    id: 'prost',
    name: 'prost',
    description: 'Protocol Buffers for Rust',
    icon: '📐',
    category: 'Rust Ecosystem',
    color: '#A0522D',
  },
  {
    id: 'sled',
    name: 'sled',
    description: 'Embedded database used in TrackForce',
    icon: '🌱',
    category: 'Database',
    color: '#6B8E23',
  },
  {
    id: 'leptos',
    name: 'Leptos',
    description: 'Rust WASM SPA framework — the Support & Ticketing front end',
    icon: '🔬',
    category: 'Rust Ecosystem',
    color: '#EF3939',
    website: 'https://leptos.dev',
  },
  {
    id: 'tauri',
    name: 'Tauri v2',
    description: 'Desktop shell — TrackForce for macOS, Windows and Linux from one codebase',
    icon: '🖥️',
    category: 'Cross-Platform',
    color: '#FFC131',
    website: 'https://tauri.app',
  },
  {
    id: 'opencv',
    name: 'OpenCV',
    description: 'Image and media processing from Rust',
    icon: '👁️',
    category: 'Rust Ecosystem',
    color: '#5C3EE8',
    website: 'https://opencv.org',
  },
  {
    id: 'argon2',
    name: 'argon2',
    description: 'Password hashing in the Support & Ticketing Platform',
    icon: '🔐',
    category: 'Rust Ecosystem',
    color: '#7B3F00',
  },
  {
    id: 'wasm',
    name: 'WebAssembly',
    description: 'Rust compiled to WASM for browser targets',
    icon: '🕸️',
    category: 'Cross-Platform',
    color: '#654FF0',
    website: 'https://webassembly.org',
  },
  {
    id: 'dartffi',
    name: 'dart:ffi',
    description: 'Raw FFI bindings between Dart and Rust',
    icon: '🔗',
    category: 'FFI & Interop',
    color: '#0175C2',
  },
  {
    id: 'cargokit',
    name: 'Cargokit',
    description: 'Builds Rust into Flutter plugins',
    icon: '📦',
    category: 'FFI & Interop',
    color: '#CE422B',
  },
  {
    id: 'frb',
    name: 'flutter_rust_bridge',
    description: 'Generated Rust to Dart bindings',
    icon: '🌉',
    category: 'FFI & Interop',
    color: '#02569B',
  },
  {
    id: 'protobuf',
    name: 'Protobuf',
    description: 'Wire format across the FFI and gRPC boundaries',
    icon: '📐',
    category: 'FFI & Interop',
    color: '#4285F4',
    website: 'https://protobuf.dev',
  },
  {
    id: 'channels',
    name: 'Platform Channels',
    description: 'Native platform messaging from Flutter',
    icon: '📨',
    category: 'FFI & Interop',
    color: '#42A5F5',
  },
  {
    id: 'postgres',
    name: 'PostgreSQL',
    description: 'Primary relational store, accessed via SQLx',
    icon: '🐘',
    category: 'Database',
    color: '#336791',
    website: 'https://postgresql.org',
  },
  {
    id: 'clickhouse',
    name: 'ClickHouse',
    description: 'OLAP store behind TrackForce analytics',
    icon: '📊',
    category: 'Database',
    color: '#FFCC01',
    website: 'https://clickhouse.com',
  },
  {
    id: 'mysql',
    name: 'MySQL',
    description: 'Relational database',
    icon: '🐬',
    category: 'Database',
    color: '#4479A1',
    website: 'https://mysql.com',
  },
  {
    id: 'sqlite',
    name: 'SQLite',
    description: 'Embedded relational database',
    icon: '🪶',
    category: 'Database',
    color: '#2E7DA8',
    website: 'https://sqlite.org',
  },
  {
    id: 'webrtc',
    name: 'WebRTC',
    description: 'Signaling, SDP negotiation and NAT traversal for video and screen share',
    icon: '🎥',
    category: 'Real-Time',
    color: '#8A8A8A',
    website: 'https://webrtc.org',
  },
  {
    id: 'websocket',
    name: 'WebSocket',
    description: 'Live streaming and chat via tokio-tungstenite',
    icon: '🔌',
    category: 'Real-Time',
    color: '#FF6B35',
  },
  {
    id: 'libp2p',
    name: 'libp2p',
    description: 'Peer-to-peer pubsub — the decentralized chat app',
    icon: '🕸️',
    category: 'Real-Time',
    color: '#3E7BFA',
    website: 'https://libp2p.io',
  },
  {
    id: 'grpc',
    name: 'gRPC',
    description: 'Service-to-service RPC with Protobuf',
    icon: '📞',
    category: 'Real-Time',
    color: '#5B9AB5',
    website: 'https://grpc.io',
  },
  {
    id: 'coturn',
    name: 'CoTURN',
    description: 'Self-hosted STUN/TURN for NAT traversal',
    icon: '🔄',
    category: 'Real-Time',
    color: '#2E8B57',
  },
  {
    id: 'git',
    name: 'Git',
    description: 'Version control',
    icon: '🌿',
    category: 'Tooling',
    color: '#F05032',
    website: 'https://git-scm.com',
  },
  {
    id: 'docker',
    name: 'Docker',
    description: 'Containerized services and reproducible builds',
    icon: '🐳',
    category: 'Tooling',
    color: '#2496ED',
    website: 'https://docker.com',
  },
  {
    id: 'azureblob',
    name: 'Azure Blob Storage',
    description: 'Screenshot galleries and object storage for TrackForce',
    icon: '☁️',
    category: 'Tooling',
    color: '#0089D6',
  },
  {
    id: 'firebase',
    name: 'Firebase',
    description: 'Auth, FCM push and storage across the Flutter suite',
    icon: '🔥',
    category: 'Tooling',
    color: '#FFCA28',
    website: 'https://firebase.google.com',
  },
  {
    id: 'twilio',
    name: 'Twilio',
    description: 'SMS delivery alongside native SMS in the restaurant platform',
    icon: '📱',
    category: 'Tooling',
    color: '#F22F46',
    website: 'https://twilio.com',
  },
];

// Derived from toolsData, so it fills in automatically as tools are added back.
export const toolCategories = Array.from(new Set(toolsData.map((tool) => tool.category)));
